### ISSUE TITLE
(1(2)|345)

### ISSUE THREAD

**Issue by yelloxing** [hai2007/Regexper-Visualization#1]
![下載](https://user-images.githubusercontent.com/23074691/124371688-dc1d5300-dcb6-11eb-84ee-89f8ee5d6c7a.png)

**Comment by hai2007** [comment]
0.1.2 开始进行了修复

**Comment by hai2007** [comment]
https://hai2007.github.io/Regexper-Visualization/?express=(1(2)%7C345)&isString=no
